### ISSUE TITLE
How do I build this thing?

### ISSUE THREAD

**Issue by yijinyang** [robojumper/DarkestDungeonSaveEditor#15]
I did a bit of androidstudio before, made a few widgets here and there. I am trying to build this program but I can't seem to do it through androidstudio. I have Java and the latest androidstudio installed. I can't seem to follow the instructions for building so I decided to try my luck here (before heading over to StackOverflow and get my question marked as duplicate).
Can anyone help? Thanks!

**Comment by robojumper** [comment]
https://github.com/robojumper/DarkestDungeonSaveEditor/blob/master/README.md#building

Additionally, standard Gradle commands are supported (`./gradlew run`, `./gradlew test`, ...).

You may be able to use your IDE's Gradle plugin to have the Gradle commands as buttons in the GUI.

**Comment by yijinyang** [comment]
> https://github.com/robojumper/DarkestDungeonSaveEditor/blob/master/README.md#building
> 
> Additionally, standard Gradle commands are supported (`./gradlew run`, `./gradlew test`, ...).
> 
> You may be able to use your IDE's Gradle plugin to have the Gradle commands as buttons in the GUI.

So am I to add the line ./gradlew fatJar into the gradlew batch file?
I tried adding this:
```
cd C:\Users\<username>\Desktop\DarkestDungeonSaveEditor-master
./gradlew fatJar
```
before running it. The window that pops up says something about building it successfully but I can't find the jar file.
What am I doing wrong?

**Comment by robojumper** [comment]
You're not supposed to edit the `gradlew` file. Instead, open a command line (`cmd`, `powershell`) in the repository root, and run `gradlew fatJar` (for cmd) or `./gradlew fatJar` (powershell). This will keep the console window open, allowing you to read any build process messages. The resulting jar file will be in `DarkestDungeonSaveEditor-master/build/libs/DDSaveEditor.jar`.

**Comment by yijinyang** [comment]
Thank you so much for your help, it slipped my mind.
