### ISSUE TITLE
May u show were u decoded files files?

### ISSUE THREAD

**Issue by CreateLab** [robojumper/DarkestDungeonSaveEditor#19]
I'm interested in   your program, but have some problems with java
May u show where u decoded *.json files
Or explain how u do it?

**Comment by robojumper** [comment]
Are you interested in a guide on how to use this program, or are you interested in the actual algorithm to decode save files? If for the former, there's not a step-by-step guide right now, unfortunately. In the latter case:

The code that *decodes* the files is in [file/DsonFile.java](https://github.com/robojumper/DarkestDungeonSaveEditor/blob/master/src/main/java/de/robojumper/ddsavereader/file/DsonFile.java) and [file/DsonField.java](https://github.com/robojumper/DarkestDungeonSaveEditor/blob/master/src/main/java/de/robojumper/ddsavereader/file/DsonField.java).

The code that *encodes* save files is in [file/DsonWriter.java](https://github.com/robojumper/DarkestDungeonSaveEditor/blob/master/src/main/java/de/robojumper/ddsavereader/file/DsonWriter.java).

As for how to do it, I documented the format in [docs/dson.md](https://github.com/robojumper/DarkestDungeonSaveEditor/blob/master/docs/dson.md). It should be possible to write an alternative decoding and encoding implementation based on that document.

Let me know if you have further questions.
