### ISSUE TITLE
`UnknownField("raid_finish_quirk_monster_class_ids")`

### ISSUE THREAD

**Issue by WaffleLapkin** [robojumper/DarkestDungeonSaveEditor#21]
Error while decoding `backup/persist.raid.json` with rust wasm online decoder:
```
Error: UnknownField("raid_finish_quirk_monster_class_ids") -- error decoding, please file a GitHub issue at 
            "https://github.com/robojumper/DarkestDungeonSaveEditor/issues"
```

The file itself:
[persist.raid.json.zip](https://github.com/robojumper/DarkestDungeonSaveEditor/files/4433445/persist.raid.json.zip)

**Comment by robojumper** [comment]
Thanks for the file!

Fixed in df2b2997ddbee5c61988f2a94188ede1360ebd97, live on the browser version. For anyone running into this with the Java implementation, I'll make a new release after figuring out what to do about #20.
