### ISSUE TITLE
Remember last profile directory in profile chooser

### ISSUE THREAD

**Issue by Kinesia23** [robojumper/DarkestDungeonSaveEditor#24]
I attempted to copy the mod list from an old save into a new one (to avoid the horrible in game reordering!), made sure I included the proper braces and commas and had both the sections included where the mods are listed. (activated and persistent).
The program would not let me save the updated file.

(Since it has replaced some variables with names I wondered if this might be a reason.)

If possible it would be _really_ useful to be able to copy and paste or even reorder mods outside the game.
(Especially for testing!)

Thanks

**Comment by robojumper** [comment]
Please provide the file and the edits you made so that I can reproduce the issue. Thanks!

**Comment by Kinesia23** [comment]
So, in the process of collecting that... It worked!
So ignore the error part, no idea what went wrong.

So instead perhaps a feature request?

Since you have everything loaded and can (theoretically) load the DD font and the project thumbnails, you could make your own list of mods and allow things like multiselect to move a bunch at once or cut and paste, instead of the stupid in game scrolling.
(Could be an offshoot of the save editor if you don't want to clutter that, that just does this and backup and restore and leaves all the technical json stuff hidden from the less technical)

Oh, and currently when you browse it'd be nice if it started on the directory you already had selected instead of going back to default... Switching between profiles is a much bigger pain currently than it needs to be, trawling back through Steam directories every time.

Thanks so much for your work!

**Comment by robojumper** [comment]
> Oh, and currently when you browse it'd be nice if it started on the directory you already had selected instead of going back to default... Switching between profiles is a much bigger pain currently than it needs to be, trawling back through Steam directories every time.

This is now implemented as of [v0.0.70](https://github.com/robojumper/DarkestDungeonSaveEditor/releases/tag/v0.0.70).
