### ISSUE TITLE
Fails to parse town event "dead_hero_entries"

### ISSUE THREAD

**Issue by noonoox** [robojumper/DarkestDungeonSaveEditor#26]
`Error reading: 171: Couldn't parse field dead_hero_entries`

**Comment by robojumper** [comment]
Please share the save file that fails to parse. I have no way to fix it without that save file.

**Comment by noonoox** [comment]
https://1drv.ms/u/s!AqCEXOpylYZTgswu0MlLFkb4ui1-Og?e=ua2OwN

**Comment by robojumper** [comment]
Thanks! Fixed in ad65f0a, `v0.0.69`. I noticed another error in my code (#27), though this is arguably the game's fault for producing invalid UTF-8.
