### ISSUE TITLE
ID table

### ISSUE THREAD

**Issue by alphageneric** [robojumper/DarkestDungeonSaveEditor#41]
Do you happen to have a table of what IDs represents in class_id, building_id, etc? They aren't readable otherwise.

For example:
| Class ID | Class Name |
| ----------- | ----------- |
| 1181166609 | Crusader |
| 2094671029 | Highwayman |

**Comment by alphageneric** [comment]
Nvm, I found the conversion method in your docs and made one myself. Thanks.

**Comment by robojumper** [comment]
Do note that the Java version includes a program to read all the game and mod data to extract those names: https://github.com/robojumper/DarkestDungeonSaveEditor/blob/master/src/main/java/de/robojumper/ddsavereader/util/ReadNames.java (there is a popup at the first launch and you can open it via the toolbar). The editor will then "unhash" those names and replace the numeric ids with specially formatted strings, e.g. "###crusader".

**Comment by alphageneric** [comment]
Ooh that's pretty cool. I've only been using the CLI part to decode files for my own downstream purposes.

**Comment by robojumper** [comment]
`ReadNames` can be run from the CLI too: `java -jar DDSaveEditor.jar names [dir1] [dir2] [dir3] [...]`.
A file containing all those names can be provided to the decoder with the `-n` or `--names` flag so that it performs this "unhashing".
