### ISSUE TITLE
DLC CC decode persist.raid.json (Error reading: Couldn't parse field backgroundNames)

### ISSUE THREAD

**Issue by b100InstKill** [robojumper/DarkestDungeonSaveEditor#9]
[persist.raid.zip](https://github.com/robojumper/DarkestDungeonSaveEditor/files/3234021/persist.raid.zip)

Help, how to fix ?

**Comment by robojumper** [comment]
v0.0.65 is available here with the fixes: https://github.com/robojumper/DarkestDungeonSaveEditor/releases/tag/v0.0.65

Thanks for reporting the issue and attaching the failing file.

**Comment by b100InstKill** [comment]
Big thx ! very fast update !!!
